name: Build Worker
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-worker.yml
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        include:
          # - { tag: nanoserver-1809,     runs-on: windows-latest, os: win,   arch: x64, args: /p:ContainerBaseImage=mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-1809 }
          # - { tag: nanoserver-ltsc2022, runs-on: windows-latest, os: win,   arch: x64, args: /p:ContainerBaseImage=mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-ltsc2022" }
          # - { tag: nanoserver-ltsc2025, runs-on: windows-latest, os: win,   arch: x64, args: /p:ContainerBaseImage=mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-ltsc2025 }
          # - { tag: linux-arm64,         runs-on: ubuntu-latest,  os: linux, arch: arm64 }
          - { tag: linux-x64,           runs-on: ubuntu-latest,  os: linux, arch: x64 }
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Login container
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USERNAME }} ${{ vars.DOCKER_REGISTRY }} --password-stdin

    - name: Build container
      run: |
        dotnet publish ./src/Sdcb.CSharpRunner.Worker/Sdcb.CSharpRunner.Worker.csproj -c Release --os ${{ matrix.os }} --arch ${{ matrix.arch }} /t:PublishContainer /p:ContainerRepository=worker ${{ needs.build-fe.outputs.msbuild_args }} ${{ matrix.args }}

    - name: Tag container with run number
      run: |
        docker tag worker ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/csharp-runner-worker:r-${{ github.run_number }}-${{ matrix.tag }}
        
    - name: Push container
      run: |
        docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/csharp-runner-worker:r-${{ github.run_number }}-${{ matrix.tag }}